---
collections:
  - name: ansible.utils
    version: 3.1.0
  - name: community.general
    version: 7.0.1
  - name: community.mysql
    version: 3.7.1
  - name: advanova.base
    version: ">=0.0.0"

